import os

env = Environment(
    CPPPATH = ['#..', '#.'],
    LIBPATH = ['#../gtest', '#../build/log', '#../build/fusion', '#../build/lua'],
    LIBS = ['pthread', 'rt', 'gtest_main', 'kulog', 'kufusion', 'kulua'],
    CCFLAGS = '-Wall --std=c++0x -g -fPIC'
    )
Export('env')

SConscript('util/SConscript')
SConscript('fusion/SConscript')
#env.Program('log', Glob('log/*.cpp'))
#env.Program('lua', Glob('lua/*.cpp'))


