import os

env = Environment(
    CPPPATH = ['..', '../..'],
    LIBPATH = ['../../gtest'],
    LIBS = ['pthread', 'gtest_main'],
    CCFLAGS = '-Wall --std=c++0x -g -fPIC'
    )

Export('env')
#SConscript('fusion/SConscript')
#SConscript('log/SConscript')
SConscript('util/SConscript')
SConscript('lua/SConscript')

"""
program = env.Program('test', 'TestMain.cpp')
test_alias = Alias('test', [program], program[0].path)
AlwaysBuild(test_alias)
"""

