import os

env = Environment(
    CPPPATH = ['#..'],
    LIBS = ['pthread'],
    CCFLAGS = '-Wall --std=c++0x -g -fPIC'
    )

Export('env')
SConscript('fusion/SConscript', variant_dir = 'build/fusion', duplicate = 0)
SConscript('log/SConscript', variant_dir = 'build/log', duplicate = 0)


