import os

env = Environment()
env.Append(HOME = os.environ['HOME'])
KUDIR = env['HOME'] + '/Dropbox/Code/Ku/'

env = Environment(
    CCFLAGS = '-Wall --std=c++0x -fPIC',
    CPPPATH = [KUDIR],
    LIBS = ['pthread'],
    )

env.Program('echo_server', Glob('*.cpp')
    )
