import os

env = Environment()
env.Append(HOME = os.environ['HOME'])
KUDIR = env['HOME'] + '/Dropbox/Code/Ku/'

env = Environment(
    CCFLAGS = '-Wall --std=c++0x -fPIC',
    CPPPATH = [KUDIR],
    LIBPATH = [KUDIR + 'ku/net/'],
    LIBS = ['pthread', 'kunet'],
    )

env.Program('timer', 'timer.cpp')
env.Program('echo_server', 'echo_server.cpp')
env.Program('echo_client', 'echo_client.cpp')

