import os

HOME = os.environ['HOME']
KUDIR = HOME + '/Dropbox/Code/Ku/'

env = Environment(
    CPPPATH = KUDIR,
    LIBS = ['pthread'],
    CCFLAGS = '-Wall --std=c++0x -g -fPIC'
    )

#env.Program('dan', Glob('*.cpp') + [KUDIR + 'gtest/gtest_main.a'])
env.Library('kunet', Glob('*.cpp'))

